name: cheep
version: '0.1.6'
summary: Be a Gamer without Paying a Fortune!!
description: Cheep Is a Program For Cleanup, Modify, Boost Your Computer, Rec And Stream Your Screen And More!!

grade: devel
confinement: devmode
parts:
  my-part:
    plugin: nil
